from enum import Enum


class Operation(Enum):
    SYSTEM_DEBUG = -2
    CLIENT_DEBUG = -1
    JOIN_NETWORK = 0
    LEAVE_NETWORK = 1
    CREATE_ACCOUNT_INIT = 2
    VOTE_SESSION_INIT = 3
    VOTE_SESSION_QUERY = 4
    REPLY = 5
    FREEZE_ACCOUNT = 6
    UPDATE_ACCOUNT = 7
    JOIN_ACTIVITY = 8
    UPDATE_ACTIVITY = 9
    SIGN_ACTIVITY = 10
    LEAVE_ACTIVITY = 11
    COMMIT_ACTIVITY = 12
    CLEAR_PAYMENT_INIT = 13
    CLEAR_PAYMENT_CONFIRM = 14
    JOIN_ACTIVITY_DATA = 15
